export const FETCH_REPO = 'FETCH_REPO'
  export const FETCH_REPO_SUCCESS = 'FETCH_REPO_SUCCESS'
  export const FETCH_REPO_FAILED = 'FETCH_REPO_FAILED'
export const FETCH_REPO_COMMENTS = "FETCH_REPO_COMMENTS"
export const FETCH_REPO_ISSUES = "FETCH_REPO_ISSUES"

export const FETCH_ISSUE = "FETCH_ISSUE"
export const FETCH_ISSUE_COMMENTS = "FETCH_ISSUE_COMMENTS"

export const LOGGED_IN = 'LOGGED_IN'
export const LOG_OUT = 'LOG_OUT'